name: CI/CD FastAPI App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name:  Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        export PYTHONPATH=.
        pytest

    - name: Build Docker image
      run: docker build -t fastapi-math-api .

    - name: Docker Hub login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push image to Docker Hub
      run: |
        docker tag fastapi-math-api ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-math-api:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-math-api:latest
